const router = require('koa-router')()
const User  = require('../controllers/user')
const Tags = require('../controllers/tags')
const Article = require('../controllers/article')
const checkToken = require('../token/checkToken')
router.post('/admin/login', User.loginPost)
router.post('/admin/checkPrepass', checkToken, User.checkPrepass)
router.post('/admin/changePass', checkToken, User.changePass)
router.post('/admin/getTags', checkToken, Tags.getTags)
router.post('/admin/removeTag', checkToken, Tags.removeTag)
router.post('/admin/addTag', checkToken, Tags.addTag)
router.get('/admin/getDraft', Article.getDraft)
router.post('/admin/saveDraft',checkToken, Article.saveDraft)
router.post('/admin/writeArticle', checkToken, Article.writeArticle)
router.post('/admin/uploadArticleImg', checkToken, Article.uploadArticleImg)
router.get('/admin/getArticleList', Article.getArticleList)
router.post('/admin/uploadArticle',checkToken, Article.uploadArticle)
router.post('/admin/updateArticleVerify',checkToken, Article.updateArticleVerify)
router.post('/admin/getArticleById',checkToken, Article.getArticleById)
router.post('/admin/uploadArticleTumbImg',checkToken, Article.uploadArticleTumbImg)

module.exports = router
