const router = require('koa-router')()
const User  = require('../controllers/user')
const Tags = require('../controllers/tags')
const Article = require('../controllers/article')
const Tool = require('../controllers/tool')
const Comment = require('../controllers/comment')
const Project = require('../controllers/project')
const About = require('../controllers/about')
const checkToken = require('../token/checkToken')

router.post('/admin/login', User.loginPost)
router.post('/admin/checkPrepass', checkToken, User.checkPrepass)
router.post('/admin/changePass', checkToken, User.changePass)
router.post('/admin/addManager', checkToken, User.addManager)
router.get('/admin/getTags', Tags.getTags)
router.post('/admin/removeTag', checkToken, Tags.removeTag)
router.post('/admin/addTag', checkToken, Tags.addTag)
router.get('/admin/getDraft', Article.getDraft)
router.post('/admin/saveDraft',checkToken, Article.saveDraft)
router.post('/admin/writeArticle', checkToken, Article.writeArticle)
router.post('/admin/uploadArticleImg', checkToken, Article.uploadArticleImg)
router.get('/admin/getArticleList', Article.getArticleList)
router.post('/admin/uploadArticle',checkToken, Article.uploadArticle)
router.post('/admin/updateArticleVerify',checkToken, Article.updateArticleVerify)
router.get('/admin/getArticleById', Article.getArticleById)
router.post('/admin/uploadArticleTumbImg',checkToken, Article.uploadArticleTumbImg)
router.post('/admin/deleteArticle',checkToken, Article.deleteArticle)
router.post('/admin/updateArticle',checkToken, Article.updateArticle)
router.get('/admin/getTools', Tool.getTools)
router.post('/admin/deleteTool', checkToken, Tool.deleteTool)
router.post('/admin/updateTool', checkToken, Tool.updateTool)
router.post('/admin/addTool', checkToken, Tool.addTool)
router.post('/toComment', Comment.toComment)
router.post('/toAgree', Comment.toAgree)
router.post('/getCommentsById', Comment.getCommentsById)
router.post('/deleteComment', Comment.deleteComment)
router.get('/getProjects', Project.getProjects)
router.get('/getAbout', About.getAbout)
module.exports = router
